name: FastAPI Docker CI/CD

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout source code
        uses: actions/checkout@v4

     
      - name: Check Docker version
        run: docker --version

      - name: Deploy to Server using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connected to server"

            cd /var/www/jktech_backend_book_management_with_agent

            echo "Pulling latest code"
            git pull origin main

            echo "Stopping old containers"
            docker-compose down

            echo "Building & starting containers"
            docker-compose up --build -d

            echo "Deployment completed"
